environment:
  stage: environment
  image: docker
  # when: manual
  variables:
    GIT_SUBMODULE_STRATEGY: none  # no need to fetch submodules
    CONTAINER_NAME: "$CI_REGISTRY/satoshilabs/trezor/trezor-firmware/environment"
  services:
    - docker:dind
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    # - docker pull $CONTAINER_NAME:latest || true
    - docker build --tag $CONTAINER_NAME:test ci/
    - docker push $CONTAINER_NAME:test
    # - docker push $CONTAINER_NAME:latest
